---
author: Dan Kelley
title: Solar angles for Chankillo observatory
bibliography: chankillo.bib
date: "`r Sys.Date()`"
---

# chankillo

Solar observatory at Chankillo, Peru

# Methods

## Digitizing Site Map

The site map in Figure 2 of @ghezzi_chankillo_2007 was viewed in MacOS Preview,
captured with the MacOS snapshot app, and then the observatory coordinates were
digitized using the imageDigitizer R function
[@kelley_dankelleyimagedigitizer_2020].

To determine scales, it had to be assumed that this diagram was prepared using
natural scaling, because otherwise it would not be possible to infer a scale
for the northing coordinate, given just a single marked value on the axis.

Although the position of the eastern observation location was indicated well on
the diagram, the same could not e said of the position of the western one.  I
elected to digitize a point on the main diagram that was in the middle of the
region shown in the inset that relates to the point.  If I had to guess, I'd
say that this is perhaps within 50m of the true location.

The towers that had been built-up on the ridge are indicated with squares in
the original diagram, and rather than try to digitize their corners, I simply
digitized one point at the centre of each.

## Solstice Indicators

@ghezzi_chankillo_2007 indicate that declinations that, in this location and at
the time 300 BCE, the solar declinations at Summer and Winter solstice were
23.75 and -23.75, respectively. These lines are indicated in the diagram.

The solstice sighting lines in the present analysis match up only approximately
with those in Figures 4 and 5 of @ghezzi_chankillo_2007.  Looking just at the
limits, I judge the mismatches to be approximately 30m.  From Figures 4 and 5
of @ghezzi_chankillo_2007, and tracing the slanted lines of the sun, this does
not seem to be explainable in terms of the elevation along the ridge.

Since I had to make a guess on the x-y scaling (given the provision of just one
labelled point along the northing direction), it is possible that the x-y
scaling of my diagram is incorrect. Another problem is my confusion on exactly
where to place the western observation location.  It might be worth looking for
other publications by these authors, to get more information on the geometry.


```{r echo=FALSE, fig.cap="Figure 1 site map, with solstice sighting lines. The Western and Eastern observation locations are indicated with labelled circle and triangle, respectively, and the crosses indicate the centres of the ridge towers. The red lines indicate sunrise and set locations at the June solstice and the blue lines indicate the same, for the December solstice."}
source("fig01.R")
```

# References



